language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE mtracker_test;" -U postgres
  - psql -c "CREATE USER tests WITH PASSWORD 'testdb';" -U postgres


script:
  - nosetests --with-coverage  --cover-package=app && coverage report

after_success:
  - coveralls